export const ActionTypes =
{
    CHECK_LOGGED: 'CHECK_LOGGED',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOGOUT_FAIL: 'LOGOUT_FAIL',

    GET_USER_DATA: 'GET_USER_DATA',

    REGISTER_ATTEMPT: 'REGISTER_ATTEMPT',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',


    SET_PROFILE: 'FETCH_PROFILE',
    PROFILE_UPDATE_ATTEMPT: 'PROFILE_UPDATE_ATTEMPT',
    PROFILE_UPDATE_FAIL: 'PROFILE_UPDATE_FAIL',
    PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',




    UPLOAD_STORY_ATTEMPT: 'UPLOAD_STORY_ATTEMPT',
    UPLOAD_STORY_SUCCESS: 'UPLOAD_STORY_SUCCESS',
    UPLOAD_STORY_FAIL: 'UPLOAD_STORY_FAIL',


    FETCH_ALL_STORIES_ATTEMPT: 'FETCH_ALL_STORIES_ATTEMPT',
    FETCH_ALL_STORIES_SUCCESS: 'FETCH_ALL_STORIES_SUCCESS',
    FETCH_ALL_STORIES_FAIL: 'FETCH_ALL_STORIES_FAIL',
    SET_STATUS: 'SET_STATUS',
    UNSET_STATUS: 'UNSET_STATUS',
    SET_CURRENT_STORY: 'SET_CURRENT_STORY',

    FETCH_ALL_WRITER_STORIES_ATTEMPT: 'FETCH_ALL_WRITER_STORIES_ATTEMPT',
    FETCH_ALL_WRITER_STORIES_SUCCESS: 'FETCH_ALL_WRITER_STORIES_SUCCESS',

    FETCH_ALL_PROJECTS_ATTEMPT: 'FETCH_ALL_PROJECTS_ATTEMPT',
    FETCH_ALL_PROJECTS_SUCCESS: 'FETCH_ALL_PROJECTS_SUCCESS',
    FETCH_ALL_PROJECTS_FAIL: 'FETCH_ALL_PROJECTS_FAIL',

    SET_CURRENT_FILE: 'SET_CURRENT_FILE',

    FETCH_SCOUT_DASHBOARD_ATTEMPT: 'FETCH_SCOUT_DASHBOARD_ATTEMPT',
    FETCH_SCOUT_DASHBOARD: 'FETCH_SCOUT_DASHBOARD',
    FETCH_SCOUT_DASHBOARD_FAIL: 'FETCH_SCOUT_DASHBOARD_FAIL',

    FETCH_WRITER_DASHBOARD_ATTEMPT: 'FETCH_WRITER_DASHBOARD_ATTEMPT',
    FETCH_WRITER_DASHBOARD: 'FETCH_WRITER_DASHBOARD',
    FETCH_WRITER_DASHBOARD_FAIL: 'FETCH_WRITER_DASHBOARD_FAIL',

    REVERT_TO_WRITER: 'REVERT_TO_WRITER',
    REVERT_TO_WRITER_FAIL: 'REVERT_TO_WRITER_FAIL',

    CLEAR_MESSAGE: 'CLEAR_MESSAGE',



}